import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import "@/little-paradise-case-study.css";

export const Route = createFileRoute("/work/little-paradise")({
  head: () => ({ meta: [
    { title: "Little Paradise Budva — Responsive Website | Rabia Naveed" },
    { name: "description", content: "A coastal hospitality website case study: original desktop, tablet and mobile designs for Little Paradise Budva." },
  ] }),
  component: LittleParadiseCaseStudy,
});
const base = "/case-studies/little-paradise/";
const sizes = { desktop: [1442, 8196], tablet: [1280, 8199], mobile: [402, 10125], "responsive-mockup": [3875, 2550], "editorial-mockup": [3841, 2259], "device-mockup": [3827, 2837] } as const;
type Asset = keyof typeof sizes;
function Shot({ name, alt, eager = false }: { name: Asset; alt: string; eager?: boolean }) {
  return <img src={base + name + (name.includes("mockup") ? ".jpg" : ".png")} alt={alt} width={sizes[name][0]} height={sizes[name][1]} loading={eager ? "eager" : "lazy"} decoding="async" draggable={false} />;
}
function Crop({ y, h, x = 0, w = 1442, name = "desktop", caption }: { y: number; h: number; x?: number; w?: number; name?: "desktop" | "tablet" | "mobile"; caption: string }) {
  return <figure className="lp-detail"><div className="lp-crop" style={{ aspectRatio: `${w}/${h}`, maxWidth: w }}><img src={base + name + ".png"} alt={caption} width={sizes[name][0]} height={sizes[name][1]} loading="lazy" decoding="async" draggable={false} style={{ width: `${sizes[name][0] / w * 100}%`, left: `${-x / w * 100}%`, top: `${-y / h * 100}%` }} /></div><figcaption>{caption}</figcaption></figure>;
}
function Heading({ label, title, copy }: { label: string; title: string; copy?: string }) {
  return <div className="lp-heading"><div><p className="lp-label">{label}</p><h2>{title}</h2></div>{copy && <p className="lp-copy">{copy}</p>}</div>;
}
const stages = [
  ["Discovery", "Defined the page goals and gathered the essentials: location, room types, amenities and ways to contact the host."],
  ["Research", "Reviewed apartment and hotel websites in Budva and similar coastal destinations to understand what travelers look for first."],
  ["Information architecture", "Organized one clear page around property highlights, apartment imagery, guest feedback and booking actions."],
  ["Wireframing", "Explored layout, hierarchy and scroll flow before introducing the final visual styling."],
  ["Visual design", "Combined a coastal palette, large photography and Poppins typography for a warm, modern welcome."],
  ["Responsive design", "Adapted content, imagery and calls to action for desktop, tablet and mobile."],
];
function LittleParadiseCaseStudy() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-md"><nav aria-label="Case study navigation" className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 text-sm font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4" /> Back to work</Link><Link to="/" hash="contact" className="text-sm font-semibold hover:text-brand">Let's talk</Link></nav></header>
    <main className="little-paradise-case">
      <section className="lp-hero">
        <div className="lp-shell"><p className="lp-label">Budva, Montenegro / Responsive Hospitality Website</p><div className="lp-hero-title"><h1>Little Paradise<br /><span>Budva.</span></h1><p>A warm, responsive web experience designed to help travelers explore the property, build trust and move easily toward booking.</p></div><div className="lp-tags"><span>UI/UX Design</span><span>Responsive Web Design</span><span>Hospitality</span><span>Landing Page</span></div></div>
        <figure className="lp-hero-image"><Shot name="responsive-mockup" eager alt="Little Paradise Budva original desktop, mobile and tablet designs in a responsive device composition" /></figure>
      </section>
      <section className="lp-shell lp-section">
        <Heading label="01 / Project overview" title="Designing a digital welcome for Little Paradise." copy="Little Paradise Budva is a modern and cozy accommodation in Budva, Montenegro. The website captures the warmth, comfort and convenience of the apartments while helping visitors browse images, understand the space, read testimonials, check availability and contact the host." />
        <dl className="lp-meta">{[["Service", "UX & UI Design"], ["Platform", "Responsive Website"], ["Industry", "Hospitality / Travel"], ["Location", "Budva, Montenegro"]].map(([a,b]) => <div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl>
        <div className="lp-goal"><div><p className="lp-label">The design goal</p><h3>A clear path from discovery to booking.</h3><p className="lp-copy">Visual warmth and a clear information structure help travelers make decisions without feeling overwhelmed.</p></div><ol>{["Understand the property quickly", "Explore apartment details", "Build trust through visuals and reviews", "Make booking and contact easy", "Create a smooth mobile experience"].map(t=><li key={t}>{t}</li>)}</ol></div>
      </section>
      <section className="lp-sand"><div className="lp-shell lp-section"><Heading label="02 / Design process" title="From a place to stay to a place to discover." /><div className="lp-process">{stages.map(([title,copy],i)=><article key={title}><span className="lp-number">0{i+1}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><div className="lp-journey"><h3>A simple one-page journey.</h3><p>The structure answers visitor questions progressively: what it is, what it offers, how it looks, what guests say and how to book.</p><ol>{["Hero", "Welcome / Property Overview", "Why Choose Little Paradise", "Explore the Space", "Apartment Features", "Guest Testimonials", "Booking CTA", "Location & Contact", "Footer"].map(t=><li key={t}>{t}</li>)}</ol></div></div></section>
      <section className="lp-shell lp-section"><Heading label="03 / First impression" title="A destination, before a description." copy="Destination photography sets the scene immediately. Simple navigation, a direct introduction and the Check Availability and Book Now actions give visitors a clear starting point." /><Crop y={0} h={752} caption="The original hero / Budva photography, navigation and availability CTA" /></section>
      <section className="lp-shell lp-section lp-intro"><div><p className="lp-label">04 / Property introduction</p><h2>Comfort, with the details that matter.</h2><p className="lp-copy">Apartment photography sits alongside the practical reasons to stay: location, modern comforts, equipped apartments, parking, transfers and room to unwind.</p></div><Crop y={752} h={1450} caption="Welcome and Why Choose Little Paradise / The original property introduction" /></section>
      <figure className="lp-wide"><Shot name="editorial-mockup" alt="Original Little Paradise desktop and mobile layouts arranged as editorial page strips" /></figure>
      <section className="lp-shell lp-section"><Heading label="05 / Explore the space" title="Letting the space speak visually." copy="Large apartment photography leads the story. Lightweight apartment tabs and gallery controls help visitors explore the interiors without losing context." /><div className="lp-gallery"><Crop y={2205} h={1170} caption="Apartment tabs, interior photography and slider controls" /><div><span className="lp-big-word">Room<br />to unwind.</span><p className="lp-copy">The imagery carries the atmosphere. The interface gives it space.</p></div></div></section>
      <section className="lp-sand"><div className="lp-shell lp-section"><Heading label="06 / Stay details" title="Amenities, made easy to scan." copy="Cozy bedroom. Fully equipped kitchen. Modern bathroom. Comfortable living space. Private terrace. Each part of the stay pairs photography with a compact information block." /><div className="lp-amenities"><Crop y={3400} h={1130} caption="Bedroom, kitchen and bathroom / Photography paired with amenity details" /><Crop y={4530} h={1180} caption="Living space and terrace / A consistent rhythm of imagery and information" /></div></div></section>
      <section className="lp-shell lp-section"><Heading label="07 / Guest trust" title="Reassurance before the next step." copy="The original guest testimonials add a layer of social proof before the booking call to action." /><Crop y={5775} h={570} caption="What Our Guests Say / Testimonials from the supplied design" /><div className="lp-booking"><div><p className="lp-label">08 / Booking</p><h3>A clear moment to act.</h3><p className="lp-copy">A coastal-blue section creates a visual pause and brings the primary booking action back into focus.</p></div><Crop y={6345} h={420} caption="Book Your Stay / The original booking call to action" /></div></section>
      <section className="lp-shell lp-section lp-contact"><Crop y={6765} h={1130} caption="Location and contact / Map, enquiry fields and Send Message action" /><div><p className="lp-label">09 / Contact & location</p><h2>One place to find the way. And get in touch.</h2><p className="lp-copy">Location context and a simple enquiry form close the journey, giving travelers a straightforward way to contact the host.</p></div></section>
      <section className="lp-blue"><div className="lp-shell lp-section"><Heading label="10 / Responsive design" title="Designed across every breakpoint." copy="The interface adapts rather than simply shrinking. Content stacks naturally, imagery remains prominent and calls to action stay accessible across desktop, tablet and mobile." /><div className="lp-devices">{(["desktop","tablet","mobile"] as const).map(name=><figure key={name} className={"lp-device lp-device-"+name}><div><Shot name={name} alt={name+" opening viewport of the original Little Paradise website"} /></div><figcaption>{name}</figcaption></figure>)}</div></div></section>
      <section className="lp-shell lp-section"><Heading label="11 / Mobile experience" title="For travelers on the move." copy="Compact navigation, stacked property details and a clear path through imagery, amenities, reviews and contact keep the mobile experience focused." /><div className="lp-mobile-scenes"><Crop name="mobile" w={402} y={0} h={1080} caption="Arrive / Navigation, hero and introduction" /><Crop name="mobile" w={402} y={2840} h={1080} caption="Explore / Apartment gallery and stay details" /><Crop name="mobile" w={402} y={6960} h={1320} caption="Decide / Guest feedback and booking" /></div><div className="lp-tablet"><div><p className="lp-label">12 / Tablet experience</p><h2>A balanced intermediate layout.</h2><p className="lp-copy">The tablet design keeps the spacious desktop feel while adapting content blocks and image proportions to a narrower viewport.</p></div><Crop name="tablet" w={1280} y={740} h={1470} caption="Tablet / Property introduction and apartment highlights" /></div></section>
      <section className="lp-sand"><div className="lp-shell lp-section"><Heading label="13 / Visual language" title="A calm coastal palette." copy="Warm sand, muted coral, coastal blue and clean white preserve the original visual identity." /><div className="lp-palette">{[["Primary","#E6D5B8"],["Accent","#D98E73"],["Secondary","#4A89AA"],["Background","#FFFFFF"]].map(([label,color])=><div key={color}><span style={{background:color}} /><p>{label}<br /><strong>{color}</strong></p></div>)}</div><div className="lp-type"><div><p className="lp-label">Typography</p><h2>Poppins</h2><p className="lp-copy">Simple, friendly and readable across every screen.</p></div><div><p style={{fontWeight:300}}>Light / A place to unwind.</p><p style={{fontWeight:400}}>Regular / Feel at home.</p><p style={{fontWeight:500}}>Medium / Explore Budva.</p><small>ABCDEFGHIJKLMNOPQRSTUVWXYZ<br />abcdefghijklmnopqrstuvwxyz / 0123456789</small></div></div></div></section>
      <section className="lp-shell lp-section"><Heading label="14 / UI details" title="Small details, consistent experience." /><div className="lp-details"><Crop x={205} y={2480} w={1030} h={155} caption="Gallery / Apartment selection" /><Crop x={170} y={5920} w={530} h={330} caption="Trust / Guest quote and attribution" /><Crop x={857} y={7000} w={390} h={775} caption="Enquiry / Labels, fields and action" /></div></section>
      <figure className="lp-wide lp-final-mockup"><Shot name="device-mockup" alt="Supplied laptop and phone mockup showing property highlights, gallery and contact design" /></figure>
      <section className="lp-full"><div className="lp-shell lp-section"><Heading label="15 / Full-page design" title="The complete experience." copy="The original desktop, tablet and mobile designs, preserved from the first welcome to the final contact details." /><div className="lp-full-pages">{(["desktop","tablet","mobile"] as const).map(name=><figure key={name}><p className="lp-label">{name}</p><Shot name={name} alt={"Complete, uncropped Little Paradise Budva "+name+" website design"} /><figcaption>Original {name} design / Full page</figcaption></figure>)}</div></div></section>
      <section className="lp-shell lp-section lp-outcome"><p className="lp-label">16 / Design outcome</p><h2>A warm, responsive hospitality experience.</h2><p className="lp-copy">Destination imagery, apartment details, social proof and clear booking actions come together in one responsive landing page built around the needs of travelers.</p><div className="lp-closing"><h3>Little Paradise Budva</h3><p>Responsive Hospitality Website<br />UX & UI Design</p><p>Designed to make every stay feel welcoming before it begins.</p></div></section>
    </main>
    <footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-6 px-5 py-12 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4" /> Explore more work</Link><Link to="/" hash="contact" className="inline-flex items-center gap-2 font-semibold text-brand">Have a project in mind? <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></footer>
  </div>;
}
