import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import "@/brida-stone-case-study.css";
export const Route = createFileRoute("/work/brida-stone")({
  head: () => ({ meta: [{ title: "Brida Stone — Website Redesign | Rabia Naveed" }, { name: "description", content: "Brida Stone responsive e-commerce redesign: product discovery, wireframes, components and the original landing-page design." }] }),
  component: BridaStone,
});
const root = "/case-studies/brida-stone/";
const assets = { "landing-page.png": [2160,10779], "responsive.jpg": [2403,1443], "wireframe-comparison.jpg": [1747,4000], "components.jpg": [2403,1211], "typography-colors.jpg": [2403,2442] } as const;
function Image({ name, alt, eager = false }: { name: keyof typeof assets; alt: string; eager?: boolean }) {
  return <img src={root+name} alt={alt} width={assets[name][0]} height={assets[name][1]} draggable={false} loading={eager ? "eager" : "lazy"} decoding="async" />;
}
function Crop({ y, h, x=0, w=1440, caption }: { y:number;h:number;x?:number;w?:number;caption:string }) {
  return <figure><div className="bs-crop" style={{aspectRatio:w+"/"+h}}><img src={root+"landing-page.png"} alt={caption} width={2160} height={10779} draggable={false} loading="lazy" style={{width:1440/w*100+"%",left:-x/w*100+"%",top:-y/h*100+"%"}} /></div><figcaption>{caption}</figcaption></figure>;
}
function Heading({ n,title,copy }: {n:string;title:string;copy?:string}) {
  return <div className="bs-heading"><div><p className="bs-label">{n}</p><h2>{title}</h2></div>{copy&&<p className="bs-copy">{copy}</p>}</div>;
}
function BridaStone(){
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-md"><nav aria-label="Case study navigation" className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 text-sm font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4"/> Back to work</Link><Link to="/" hash="contact" className="text-sm font-semibold hover:text-brand">Let's talk</Link></nav></header>
    <main className="brida-case">
      <section className="bs-hero"><div className="bs-shell"><p className="bs-label">Natural stone / Responsive e-commerce</p><div className="bs-hero-title"><h1>Brida Stone <em>Inc.</em></h1><div><p className="bs-label">Website Redesign</p><p>A modern e-commerce redesign created to make natural stone products easier to discover, explore and shop.</p></div></div><div className="bs-tags"><span>UI/UX Design</span><span>Website Redesign</span><span>E-commerce</span><span>Responsive Design</span></div></div><figure className="bs-hero-visual"><Image name="responsive.jpg" eager alt="Supplied Brida Stone desktop, tablet and mobile design mockups"/></figure></section>
      <section className="bs-shell bs-section"><Heading n="01 / Overview" title="A clearer digital experience for a traditional stone business." copy="Brida Stone Inc. is a family-owned natural stone supplier in Glassboro, New Jersey. The redesign organizes materials for gardens, hearths, homes and outdoor spaces into a more approachable, visual browsing experience."/><dl className="bs-meta">{[["Role","UI/UX Designer"],["Project","Website Redesign"],["Category","Natural Stone / E-commerce"],["Platform","Responsive Web"]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><div className="bs-response"><div><p className="bs-label">The challenge</p><h3>Less searching.<br/>More discovering.</h3><p className="bs-copy">Text-heavy information, weak hierarchy and an unclear category structure made the product range difficult to scan. The design needed to give materials and the family business more room to tell their story.</p></div><div><p className="bs-label">The design response</p><h3>A more visual way to explore natural stone.</h3><ul><li>Clear navigation</li><li>Visual product discovery</li><li>Stronger hierarchy</li><li>Trust and heritage</li></ul></div></div></section>
      <section className="bs-stone"><div className="bs-shell bs-section"><Heading n="02 / Wireframe to final" title="From structure to visual direction." copy="The grayscale wireframe establishes content order, hierarchy and product discovery. Photography, typography and the natural color palette bring that structure into the final design."/><div className="bs-comparison"><div><p className="bs-label">Grayscale structure</p><div className="bs-wire bs-wire-left"><Image name="wireframe-comparison.jpg" alt="Original grayscale Brida Stone wireframe, cropped from the supplied comparison"/></div></div><div><p className="bs-label">Colored high-fidelity</p><div className="bs-wire bs-wire-right"><Image name="wireframe-comparison.jpg" alt="Original high-fidelity Brida Stone design, cropped from the supplied comparison"/></div></div></div><p className="bs-note">Two views from the supplied wireframe comparison.</p></div></section>
      <section className="bs-shell bs-section"><Heading n="03 / Information structure" title="A clear route through the range." copy="The top navigation separates products, promotions, editorial content and company information. The home page moves from discovery to products, inspiration and trust."/><div className="bs-nav-flow">Home <span>→</span> Products <span>→</span> Sale <span>→</span> Blog <span>→</span> About Us <span>→</span> Contact Us</div><ol className="bs-flow">{["Hero & value propositions","Product categories","Stock sale","Featured products","Create Your Dream Space","Blog","Testimonials","Contact & satisfaction","Family-owned business","Footer"].map(t=><li key={t}>{t}</li>)}</ol></section>
      <section className="bs-shell bs-section bs-first"><Heading n="04 / First impression" title="Building trust from the first screen." copy="Natural stone imagery introduces the business. Expert Guidance, High Quality, Superior Product and Innovation provide a clear set of value statements beneath the Shop Now action."/><Crop y={0} h={990} caption="Original landing-page opening / Branding, navigation, photography and value propositions"/></section>
      <section className="bs-olive"><div className="bs-shell bs-section"><Heading n="05 / Product discovery" title="A broad catalog, made easier to browse." copy="Image-led categories let customers recognize materials at a glance, from custom cut stone and thin veneer to boulders, gardenwall stone and decorative crushed stone."/><Crop y={1020} h={920} caption="Product categories / Eight visual entry points into the range"/></div></section>
      <section className="bs-shell bs-section bs-products"><div><p className="bs-label">06 / Sale & featured products</p><h2>Bringing product actions forward.</h2><p className="bs-copy">Promotions, pricing and product actions have a clearer hierarchy. Visitors can move from browsing materials toward considering a specific product.</p><p className="bs-note">Product actions shown are part of the supplied design.</p></div><div><Crop y={1950} h={650} caption="Stock Sale / A focused promotional moment"/><Crop y={2600} h={830} caption="Featured Products / Imagery, pricing and Add to Cart actions"/></div></section>
      <section className="bs-stone"><div className="bs-shell bs-section"><Heading n="07 / Inspiration & education" title="From a material to a possibility." copy="Lifestyle imagery helps visitors imagine the materials in a finished space. Blog cards add practical context around home decor, stone types and landscaping."/><Crop y={3430} h={610} caption="Create Your Dream Space / Project imagery and supporting story"/><div className="bs-blog"><Crop y={4040} h={840} caption="Our Blog / Practical ideas beyond the catalog"/></div></div></section>
      <section className="bs-shell bs-section"><Heading n="08 / Trust & heritage" title="Keeping the people behind the products visible." copy="The supplied testimonials, contact invitation and family-business section keep personal service visible alongside the product experience."/><div className="bs-trust"><Crop y={4890} h={1170} caption="Customer feedback and contact / Original testimonial content and satisfaction section"/><Crop y={6060} h={710} caption="Family Owned Business / The original team presentation"/></div></section>
      <section className="bs-stone"><div className="bs-shell bs-section"><Heading n="09 / Components & variants" title="A reusable interface system." copy="Navigation states, a blog card, testimonial content, icons and button variants keep the experience visually consistent."/><div className="bs-components"><Image name="components.jpg" alt="Original Brida Stone navigation variants, blog card, testimonial, icons and CTA components"/></div><div className="bs-details"><Crop x={150} y={2730} w={400} h={600} caption="Product detail / Image, price and action"/><Crop x={60} y={4170} w={430} h={590} caption="Editorial detail / Photography, title and View action"/></div></div></section>
      <section className="bs-shell bs-section"><Heading n="10 / Typography & color" title="Editorial character. Everyday readability." copy="Playfair Display brings a crafted, heritage-oriented character to headings. Open Sans keeps navigation, product information and actions clear."/><div className="bs-type"><div><p className="bs-label">Playfair Display</p><p>Natural materials.<br/><em>Lasting character.</em></p></div><div><p className="bs-label">Open Sans</p><p>Clear details.<br/>Simple next steps.</p></div></div><div className="bs-palette"><div>Olive & sage</div><div>Earthy brown</div><div>Charcoal</div><div>Warm stone</div></div><p className="bs-copy bs-palette-note">Muted greenery, soil tones and neutral surfaces support the photography. The color families follow the supplied project palette.</p></section>
      <section className="bs-responsive"><div className="bs-shell bs-section"><Heading n="11 / Responsive design" title="Designed to adapt naturally." copy="The supplied device views show a layout designed to keep imagery, product information and actions prominent across desktop, tablet and mobile."/><Image name="responsive.jpg" alt="Original responsive Brida Stone composition with desktop inspiration, tablet categories and mobile products"/><div className="bs-mobile-row"><div><p className="bs-label">Mobile product experience</p><h2>Product discovery on smaller screens.</h2><p className="bs-copy">The mobile view stacks featured products while keeping the image, price and Add to Cart action together.</p></div><div className="bs-mobile-crop"><Image name="responsive.jpg" alt="Focused crop of the supplied phone mockup showing Featured Products"/></div></div></div></section>
      <section className="bs-shell bs-section"><Heading n="12 / Complete landing page" title="The complete redesigned experience." copy="The original landing page, rendered directly from the supplied PDF. Presented in two consecutive sections to keep the full design visible."/><div className="bs-full"><Crop y={0} h={3593} caption="Part 1 / Introduction, categories, promotions and featured products"/><Crop y={3593} h={3593} caption="Part 2 / Inspiration, editorial content, trust, team and footer"/></div></section>
      <section className="bs-closing"><div className="bs-shell bs-section"><Heading n="13 / Design summary" title="A clearer home for a broad product catalog." copy="Stronger hierarchy, product-led imagery and a reusable interface system create a more contemporary presentation while retaining the family-owned character of the business."/><div className="bs-end"><h3>Brida Stone Inc.</h3><p>Responsive Website Redesign<br/>UI/UX Design</p><p>Natural materials.<br/>Clearer digital discovery.</p></div></div></section>
    </main><footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-6 px-5 py-12 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4"/> Explore more work</Link><Link to="/" hash="contact" className="inline-flex items-center gap-2 font-semibold text-brand">Have a project in mind? <ArrowUpRight aria-hidden="true" className="h-4 w-4"/></Link></footer>
  </div>;
}
