import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import "@/sunny-side-case-study.css";

export const Route = createFileRoute("/work/sunny-side")({
  head: () => ({ meta: [
    { title: "Sunny Side — Logo & Visual Identity | Rabia Naveed" },
    { name: "description", content: "Sunny Side logo case study: an original sunrise-inspired symbol, a bright color story and curated identity applications." },
  ] }),
  component: SunnySideCaseStudy,
});
function Logo({ small = false }: { small?: boolean }) {
  return <div className={"ss-logo" + (small ? " ss-logo-small" : "")}><img src="/case-studies/sunny-side/original-logo.jpg" alt="Original Sunny Side symbol: yellow sun rays, an orange sunrise and a cyan flowing line" width={1080} height={1080} draggable={false} /></div>;
}
function Heading({ label, title, copy }: { label: string; title: string; copy?: string }) {
  return <div className="ss-heading"><div><p className="ss-label">{label}</p><h2>{title}</h2></div>{copy && <p className="ss-copy">{copy}</p>}</div>;
}
function SunnySideCaseStudy() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-md"><nav aria-label="Case study navigation" className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 text-sm font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4" /> Back to work</Link><Link to="/" hash="contact" className="text-sm font-semibold hover:text-brand">Let's talk</Link></nav></header>
    <main className="sunny-side-case">
      <section className="ss-hero ss-shell"><div className="ss-top"><p>Sunny Side</p><p>Logo Design / Visual Identity</p></div><div className="ss-hero-mark"><Logo /></div><div className="ss-hero-bottom"><h1>A little sunshine.<br />A bright identity.</h1><p>A bright, minimal identity inspired by warmth, optimism and fresh beginnings.</p></div></section>
      <section className="ss-cream"><div className="ss-shell ss-section"><Heading label="01 / Overview" title="A simple identity built around warmth and positivity." copy="Sunny Side is a clean and approachable visual identity centered around a rising sun and a flowing line form. The goal: a mark that feels optimistic, memorable and easy to recognize." /><dl className="ss-meta"><div><dt>Project</dt><dd>Sunny Side</dd></div><div><dt>Role</dt><dd>Logo Designer</dd></div><div><dt>Discipline</dt><dd>Logo / Visual Identity</dd></div><div><dt>Approach</dt><dd>Minimal / Modern</dd></div></dl></div></section>
      <section className="ss-shell ss-section"><Heading label="02 / The concept" title="The idea behind the mark." copy="A rising sun meets a continuous flowing form. Warmth above, movement below: a simple visual expression of energy and a positive outlook." /><div className="ss-concept"><div className="ss-concept-words"><span>Sunrise.</span><span>Flow.</span><span>Optimism.</span></div><Logo /></div><div className="ss-breakdown">{[["Warmth","The orange rising sun."],["Energy","The bright yellow rays."],["Movement","The flowing cyan form."]].map(([a,b],i)=><div key={a}><span className={"ss-dot ss-dot-"+i} /><h3>{a}</h3><p>{b}</p></div>)}</div></section>
      <section className="ss-color"><div className="ss-shell ss-section"><Heading label="03 / Color story" title="A bright and uplifting palette." copy="Cool cyan balances warm orange and yellow. White gives each color room to feel fresh, clear and full of energy." /></div><div className="ss-color-fields"><div><span>01 / Ocean Blue</span></div><div><span>02 / Warm Orange</span></div><div><span>03 / Sun Yellow</span></div><div><span>04 / White</span></div></div></section>
      <section className="ss-shell ss-section"><Heading label="04 / The original symbol" title="One mark. Room to breathe." copy="The full-color icon is the core of the identity. Clear space keeps its open curves and rising sun in focus." /><div className="ss-logo-stage"><Logo /></div><div className="ss-scale"><div><Logo /><p>Large / Brand presence</p></div><div><Logo /><p>Medium / Profile use</p></div><div><Logo /><p>Small / Icon preview</p></div></div><p className="ss-footnote">Size studies using the supplied symbol.</p></section>
      <section className="ss-photo-section"><div className="ss-shell ss-photo-intro"><p className="ss-label">05 / Identity in context</p><h2>A warmer first impression.</h2></div><figure><img src="/case-studies/sunny-side/stationery-mockup.png" alt="Supplied Sunny Side stationery mockup on textured paper in warm sunlight" width={1536} height={1024} draggable={false} loading="lazy" decoding="async" /><figcaption className="ss-shell">Supplied stationery visualization / Logo, lettering and tagline shown as provided in the mockup.</figcaption></figure></section>
      <section className="ss-shell ss-section"><Heading label="06 / Digital applications" title="A familiar face, wherever it appears." copy="Two restrained digital placement studies put the original icon in everyday contexts, without building a new product around it." /><div className="ss-applications"><figure className="ss-browser"><div className="ss-browser-chrome" aria-hidden="true"><i /><i /><i /></div><div className="ss-navbar"><Logo small /><span>Sunny Side</span><span className="ss-menu" aria-hidden="true">☰</span></div><div className="ss-browser-body"><span>Fresh beginnings.</span><p>A little space for something bright.</p></div><figcaption>Concept application / Website header</figcaption></figure><figure className="ss-profile"><div className="ss-profile-top"><div className="ss-avatar"><Logo /></div><div><strong>Sunny Side</strong><p>Profile preview</p></div></div><div className="ss-profile-cover"><Logo /></div><figcaption>Concept application / Social profile</figcaption></figure></div></section>
      <section className="ss-poster"><div className="ss-shell"><p className="ss-label">An expression of the brand mood</p><h2>Look on the<br /><span>bright side.</span></h2><div className="ss-poster-mark"><Logo /></div></div></section>
      <section className="ss-shell ss-section"><Heading label="07 / Visual language" title="Simple forms. Bright personality." copy="Clean space, rounded forms and a restrained use of color carry the same simplicity as the symbol. The logo stays at the center of every composition." /><div className="ss-showcase"><div className="ss-showcase-white"><Logo /><span>Full color / White space</span></div><div className="ss-showcase-blue"><div><Logo /></div><span>Full color / Cyan surround</span></div></div></section>
      <section className="ss-cream"><div className="ss-shell ss-section"><Heading label="08 / Outcome" title="A simple mark with an optimistic feel." copy="A sunrise-inspired symbol and a bright color system keep Sunny Side friendly, fresh and adaptable across digital applications." /><div className="ss-closing"><h3>Sunny Side</h3><p>Logo Design / Visual Identity</p><span>Bright by design.</span></div></div></section>
    </main>
    <footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-6 px-5 py-12 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4" /> Explore more work</Link><Link to="/" hash="contact" className="inline-flex items-center gap-2 font-semibold text-brand">Have a project in mind? <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></footer>
  </div>;
}
