import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import "@/artify-identity.css";

export const Route = createFileRoute("/work/artify-identity")({
  head: () => ({ meta: [
    { title: "Artify — Visual Identity | Rabia Naveed" },
    { name: "description", content: "An independent Artify logo and visual identity case study. Original symbol, wordmark and Explore Engage Enjoy tagline." },
  ] }),
  component: ArtifyIdentity,
});
const source = "/case-studies/artify-identity/original-logo.jpg";
function Artwork({ part = "full" }: { part?: "full" | "symbol" | "type" | "detail" }) {
  return <div className={"ai-art ai-art-" + part}><img src={source} alt={part === "type" ? "Original ARTIFY wordmark and Explore Engage Enjoy tagline" : part === "detail" ? "Detail of the original Artify symbol and its color transitions" : part === "symbol" ? "Original flowing multicolor Artify symbol" : "Original Artify logo, wordmark and Explore Engage Enjoy tagline"} width={483} height={452} draggable={false} decoding="async" /></div>;
}
function Intro({ n, title, children }: { n: string; title: string; children?: string }) {
  return <div className="ai-intro"><p className="ai-label">{n}</p><h2>{title}</h2>{children && <p className="ai-copy">{children}</p>}</div>;
}
function ArtifyIdentity() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-md"><nav aria-label="Case study navigation" className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 text-sm font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4" /> Back to work</Link><Link to="/" hash="contact" className="text-sm font-semibold hover:text-brand">Let's talk</Link></nav></header>
    <main className="artify-identity">
      <section className="ai-shell ai-hero"><div className="ai-top"><span>Artify / Visual Identity</span><span>Independent branding project</span></div><div className="ai-hero-grid"><div><p className="ai-label">Logo Design & Visual Identity</p><h1>Creativity,<br /><em>in motion.</em></h1><p className="ai-copy">A vibrant identity built around creativity, connection and visual discovery.</p></div><Artwork /></div><div className="ai-hero-bottom"><span>Explore Engage Enjoy</span><span>Symbol / Wordmark / Color</span></div></section>
      <section className="ai-paper"><div className="ai-shell ai-section ai-overview"><Intro n="01 / Introduction" title="An identity designed to feel expressive." /><div><p className="ai-copy">Artify brings together flowing shapes and energetic color transitions in a contemporary visual identity. The abstract mark expresses creativity and movement, balanced by a clear uppercase name.</p><dl><div><dt>Role</dt><dd>Logo Designer</dd></div><div><dt>Category</dt><dd>Visual Identity</dd></div><div><dt>Style</dt><dd>Creative / Contemporary</dd></div></dl></div></div></section>
      <section className="ai-shell ai-section"><div className="ai-concept"><Intro n="02 / The idea" title="Connected forms. Open possibilities.">The connected, flowing forms suggest interaction and continuous exploration. Overlapping shapes create movement; warm and cool color transitions give the mark its expressive character.</Intro><div className="ai-symbol-space"><Artwork part="symbol" /><span className="ai-caption">The original symbol / Presented without alteration</span></div></div><div className="ai-verbs"><span>Explore</span><span>Engage</span><span>Enjoy</span></div></section>
      <section className="ai-study"><div className="ai-shell ai-section"><Intro n="03 / Symbol study" title="Expression in the details." /><div className="ai-study-grid"><div><Artwork part="symbol" /><p>Movement / The complete form</p></div><div><Artwork part="detail" /><p>Connection / Curves and negative space</p></div></div><p className="ai-study-note">Selected views of the supplied artwork, showing the overlap and color transitions already present in the mark.</p></div></section>
      <section className="ai-shell ai-section ai-wordmark"><Intro n="04 / Wordmark & tagline" title="A simple name with an expressive mark.">The uppercase wordmark grounds the composition. The lighter “Explore Engage Enjoy” tagline adds personality without competing with the symbol.</Intro><div><Artwork part="type" /><p className="ai-caption">Original lettering / Preserved from the supplied logo</p></div></section>
      <section className="ai-color"><div className="ai-shell ai-section"><Intro n="05 / Color story" title="Color as part of the personality.">Warm orange, burgundy, teal, green, golden yellow and muted purple bring variety to the identity. Cream gives the color room to breathe.</Intro><div className="ai-color-composition" aria-label="Visible color families from the Artify identity">{["Warm orange","Burgundy","Teal","Green","Golden yellow","Muted purple"].map(t=><div key={t}><span>{t}</span></div>)}</div><div className="ai-gradient-story"><div><h3>Movement through color.</h3><p className="ai-copy">The transitions follow the curves of the original symbol, connecting its forms rather than separating them.</p></div><Artwork part="detail" /></div></div></section>
      <section className="ai-shell ai-section"><Intro n="06 / Form & scale" title="The shape carries the identity." /><div className="ai-tonal"><div className="ai-tonal-mark"><Artwork part="symbol" /></div><p className="ai-copy">A grayscale presentation isolates the form. The full-color original remains the primary identity.</p></div><div className="ai-sizes">{["Large","Medium","Small"].map(t=><figure key={t}><Artwork part="symbol" /><figcaption>{t} / Symbol study</figcaption></figure>)}</div></section>
      <section className="ai-pattern"><div className="ai-shell"><p className="ai-label">07 / Extending the visual language</p><h2>A rhythm from the mark itself.</h2><div className="ai-pattern-strip">{[0,1,2,3].map(i=><Artwork key={i} part="symbol" />)}</div><p className="ai-caption">Repetition of the original symbol / No additional shapes</p></div></section>
      <section className="ai-shell ai-section"><Intro n="08 / Print applications" title="An identity with space to express itself.">Two print placement studies use the original identity on a gallery-style poster and a small correspondence card.</Intro><div className="ai-print-stage"><figure className="ai-print-poster"><p className="ai-print-kicker">A study in creative expression</p><Artwork /><div className="ai-poster-rule" /><p className="ai-print-note">Color. Connection. Possibility.</p></figure><figure className="ai-print-card"><Artwork /><figcaption>Concept application / Correspondence card</figcaption></figure></div><p className="ai-caption">Concept applications / Poster and stationery</p></section>
      <section className="ai-brand-poster"><div className="ai-shell"><p className="ai-label">09 / Brand poster</p><div className="ai-poster-composition"><p>Explore<br /><em>Engage</em><br />Enjoy</p><Artwork /></div></div></section>
      <section className="ai-shell ai-section ai-social"><Intro n="10 / Social identity" title="A recognizable signature.">A simple profile placement shows how the symbol and complete identity can sit together in a branded social presence.</Intro><figure className="ai-social-preview"><div className="ai-profile-line"><div><Artwork part="symbol" /></div><span>Artify<small>Explore Engage Enjoy</small></span></div><Artwork /><figcaption>Concept application / Social identity</figcaption></figure></section>
      <section className="ai-dark"><div className="ai-shell ai-section ai-dark-grid"><Intro n="11 / Contrast" title="Color that holds its presence.">A deep neutral surround frames the colorful identity. The original cream artwork stays intact.</Intro><Artwork /></div></section>
      <section className="ai-shell ai-section ai-finale"><Intro n="12 / Outcome" title="A colorful identity with a clear character.">An expressive symbol, a vibrant color system and a simple wordmark come together in an identity that feels creative, flexible and memorable.</Intro><div className="ai-end"><Artwork part="type" /><p>Logo Design / Visual Identity<br /><span>Created to celebrate creativity in motion.</span></p></div></section>
    </main>
    <footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-6 px-5 py-12 sm:px-8"><Link to="/" hash="work" className="inline-flex items-center gap-2 font-semibold hover:text-brand"><ArrowLeft aria-hidden="true" className="h-4 w-4" /> Back to portfolio</Link><Link to="/" hash="contact" className="inline-flex items-center gap-2 font-semibold text-brand">Have a branding project in mind? <ArrowUpRight aria-hidden="true" className="h-4 w-4" /></Link></footer>
  </div>;
}
