/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HeroPreviewRouteImport } from './routes/hero-preview'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as WorkAgrinovaRouteImport } from './routes/work.agrinova'
import { Route as WorkArtifyRouteImport } from './routes/work.artify'
import { Route as WorkArtifyIdentityRouteImport } from './routes/work.artify-identity'
import { Route as WorkBakeryRouteImport } from './routes/work.bakery'
import { Route as WorkBlissHavenRouteImport } from './routes/work.bliss-haven'
import { Route as WorkBridaStoneRouteImport } from './routes/work.brida-stone'
import { Route as WorkConsulteaseRouteImport } from './routes/work.consultease'
import { Route as WorkCothmRouteImport } from './routes/work.cothm'
import { Route as WorkDestinifyRouteImport } from './routes/work.destinify'
import { Route as WorkFidatoRouteImport } from './routes/work.fidato'
import { Route as WorkFreelaRouteImport } from './routes/work.freela'
import { Route as WorkLittleParadiseRouteImport } from './routes/work.little-paradise'
import { Route as WorkMarketeriaRouteImport } from './routes/work.marketeria'
import { Route as WorkMeridianRealtyRouteImport } from './routes/work.meridian-realty'
import { Route as WorkSunnySideRouteImport } from './routes/work.sunny-side'
import { Route as WorkTechdoseRouteImport } from './routes/work.techdose'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminProjectsIndexRouteImport } from './routes/_authenticated/admin/projects.index'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroPreviewRoute = HeroPreviewRouteImport.update({
  id: '/hero-preview',
  path: '/hero-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAgrinovaRoute = WorkAgrinovaRouteImport.update({
  id: '/work/agrinova',
  path: '/work/agrinova',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkArtifyRoute = WorkArtifyRouteImport.update({
  id: '/work/artify',
  path: '/work/artify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkArtifyIdentityRoute = WorkArtifyIdentityRouteImport.update({
  id: '/work/artify-identity',
  path: '/work/artify-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBakeryRoute = WorkBakeryRouteImport.update({
  id: '/work/bakery',
  path: '/work/bakery',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBlissHavenRoute = WorkBlissHavenRouteImport.update({
  id: '/work/bliss-haven',
  path: '/work/bliss-haven',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkBridaStoneRoute = WorkBridaStoneRouteImport.update({
  id: '/work/brida-stone',
  path: '/work/brida-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkConsulteaseRoute = WorkConsulteaseRouteImport.update({
  id: '/work/consultease',
  path: '/work/consultease',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkCothmRoute = WorkCothmRouteImport.update({
  id: '/work/cothm',
  path: '/work/cothm',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkDestinifyRoute = WorkDestinifyRouteImport.update({
  id: '/work/destinify',
  path: '/work/destinify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFidatoRoute = WorkFidatoRouteImport.update({
  id: '/work/fidato',
  path: '/work/fidato',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFreelaRoute = WorkFreelaRouteImport.update({
  id: '/work/freela',
  path: '/work/freela',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkLittleParadiseRoute = WorkLittleParadiseRouteImport.update({
  id: '/work/little-paradise',
  path: '/work/little-paradise',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkMarketeriaRoute = WorkMarketeriaRouteImport.update({
  id: '/work/marketeria',
  path: '/work/marketeria',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkMeridianRealtyRoute = WorkMeridianRealtyRouteImport.update({
  id: '/work/meridian-realty',
  path: '/work/meridian-realty',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSunnySideRoute = WorkSunnySideRouteImport.update({
  id: '/work/sunny-side',
  path: '/work/sunny-side',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkTechdoseRoute = WorkTechdoseRouteImport.update({
  id: '/work/techdose',
  path: '/work/techdose',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProjectsIndexRoute =
  AuthenticatedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/media/$': typeof MediaSplatRoute
  '/work/agrinova': typeof WorkAgrinovaRoute
  '/work/artify': typeof WorkArtifyRoute
  '/work/artify-identity': typeof WorkArtifyIdentityRoute
  '/work/bakery': typeof WorkBakeryRoute
  '/work/bliss-haven': typeof WorkBlissHavenRoute
  '/work/brida-stone': typeof WorkBridaStoneRoute
  '/work/consultease': typeof WorkConsulteaseRoute
  '/work/cothm': typeof WorkCothmRoute
  '/work/destinify': typeof WorkDestinifyRoute
  '/work/fidato': typeof WorkFidatoRoute
  '/work/freela': typeof WorkFreelaRoute
  '/work/little-paradise': typeof WorkLittleParadiseRoute
  '/work/marketeria': typeof WorkMarketeriaRoute
  '/work/meridian-realty': typeof WorkMeridianRealtyRoute
  '/work/sunny-side': typeof WorkSunnySideRoute
  '/work/techdose': typeof WorkTechdoseRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/media/$': typeof MediaSplatRoute
  '/work/agrinova': typeof WorkAgrinovaRoute
  '/work/artify': typeof WorkArtifyRoute
  '/work/artify-identity': typeof WorkArtifyIdentityRoute
  '/work/bakery': typeof WorkBakeryRoute
  '/work/bliss-haven': typeof WorkBlissHavenRoute
  '/work/brida-stone': typeof WorkBridaStoneRoute
  '/work/consultease': typeof WorkConsulteaseRoute
  '/work/cothm': typeof WorkCothmRoute
  '/work/destinify': typeof WorkDestinifyRoute
  '/work/fidato': typeof WorkFidatoRoute
  '/work/freela': typeof WorkFreelaRoute
  '/work/little-paradise': typeof WorkLittleParadiseRoute
  '/work/marketeria': typeof WorkMarketeriaRoute
  '/work/meridian-realty': typeof WorkMeridianRealtyRoute
  '/work/sunny-side': typeof WorkSunnySideRoute
  '/work/techdose': typeof WorkTechdoseRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/hero-preview': typeof HeroPreviewRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/media/$': typeof MediaSplatRoute
  '/work/agrinova': typeof WorkAgrinovaRoute
  '/work/artify': typeof WorkArtifyRoute
  '/work/artify-identity': typeof WorkArtifyIdentityRoute
  '/work/bakery': typeof WorkBakeryRoute
  '/work/bliss-haven': typeof WorkBlissHavenRoute
  '/work/brida-stone': typeof WorkBridaStoneRoute
  '/work/consultease': typeof WorkConsulteaseRoute
  '/work/cothm': typeof WorkCothmRoute
  '/work/destinify': typeof WorkDestinifyRoute
  '/work/fidato': typeof WorkFidatoRoute
  '/work/freela': typeof WorkFreelaRoute
  '/work/little-paradise': typeof WorkLittleParadiseRoute
  '/work/marketeria': typeof WorkMarketeriaRoute
  '/work/meridian-realty': typeof WorkMeridianRealtyRoute
  '/work/sunny-side': typeof WorkSunnySideRoute
  '/work/techdose': typeof WorkTechdoseRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/_authenticated/admin/projects/': typeof AuthenticatedAdminProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/hero-preview'
    | '/admin'
    | '/media/$'
    | '/work/agrinova'
    | '/work/artify'
    | '/work/artify-identity'
    | '/work/bakery'
    | '/work/bliss-haven'
    | '/work/brida-stone'
    | '/work/consultease'
    | '/work/cothm'
    | '/work/destinify'
    | '/work/fidato'
    | '/work/freela'
    | '/work/little-paradise'
    | '/work/marketeria'
    | '/work/meridian-realty'
    | '/work/sunny-side'
    | '/work/techdose'
    | '/admin/'
    | '/admin/projects/$id'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/hero-preview'
    | '/media/$'
    | '/work/agrinova'
    | '/work/artify'
    | '/work/artify-identity'
    | '/work/bakery'
    | '/work/bliss-haven'
    | '/work/brida-stone'
    | '/work/consultease'
    | '/work/cothm'
    | '/work/destinify'
    | '/work/fidato'
    | '/work/freela'
    | '/work/little-paradise'
    | '/work/marketeria'
    | '/work/meridian-realty'
    | '/work/sunny-side'
    | '/work/techdose'
    | '/admin'
    | '/admin/projects/$id'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/hero-preview'
    | '/_authenticated/admin'
    | '/media/$'
    | '/work/agrinova'
    | '/work/artify'
    | '/work/artify-identity'
    | '/work/bakery'
    | '/work/bliss-haven'
    | '/work/brida-stone'
    | '/work/consultease'
    | '/work/cothm'
    | '/work/destinify'
    | '/work/fidato'
    | '/work/freela'
    | '/work/little-paradise'
    | '/work/marketeria'
    | '/work/meridian-realty'
    | '/work/sunny-side'
    | '/work/techdose'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/projects/$id'
    | '/_authenticated/admin/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HeroPreviewRoute: typeof HeroPreviewRoute
  MediaSplatRoute: typeof MediaSplatRoute
  WorkAgrinovaRoute: typeof WorkAgrinovaRoute
  WorkArtifyRoute: typeof WorkArtifyRoute
  WorkArtifyIdentityRoute: typeof WorkArtifyIdentityRoute
  WorkBakeryRoute: typeof WorkBakeryRoute
  WorkBlissHavenRoute: typeof WorkBlissHavenRoute
  WorkBridaStoneRoute: typeof WorkBridaStoneRoute
  WorkConsulteaseRoute: typeof WorkConsulteaseRoute
  WorkCothmRoute: typeof WorkCothmRoute
  WorkDestinifyRoute: typeof WorkDestinifyRoute
  WorkFidatoRoute: typeof WorkFidatoRoute
  WorkFreelaRoute: typeof WorkFreelaRoute
  WorkLittleParadiseRoute: typeof WorkLittleParadiseRoute
  WorkMarketeriaRoute: typeof WorkMarketeriaRoute
  WorkMeridianRealtyRoute: typeof WorkMeridianRealtyRoute
  WorkSunnySideRoute: typeof WorkSunnySideRoute
  WorkTechdoseRoute: typeof WorkTechdoseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hero-preview': {
      id: '/hero-preview'
      path: '/hero-preview'
      fullPath: '/hero-preview'
      preLoaderRoute: typeof HeroPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/agrinova': {
      id: '/work/agrinova'
      path: '/work/agrinova'
      fullPath: '/work/agrinova'
      preLoaderRoute: typeof WorkAgrinovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/artify': {
      id: '/work/artify'
      path: '/work/artify'
      fullPath: '/work/artify'
      preLoaderRoute: typeof WorkArtifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/artify-identity': {
      id: '/work/artify-identity'
      path: '/work/artify-identity'
      fullPath: '/work/artify-identity'
      preLoaderRoute: typeof WorkArtifyIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/bakery': {
      id: '/work/bakery'
      path: '/work/bakery'
      fullPath: '/work/bakery'
      preLoaderRoute: typeof WorkBakeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/bliss-haven': {
      id: '/work/bliss-haven'
      path: '/work/bliss-haven'
      fullPath: '/work/bliss-haven'
      preLoaderRoute: typeof WorkBlissHavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/brida-stone': {
      id: '/work/brida-stone'
      path: '/work/brida-stone'
      fullPath: '/work/brida-stone'
      preLoaderRoute: typeof WorkBridaStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/consultease': {
      id: '/work/consultease'
      path: '/work/consultease'
      fullPath: '/work/consultease'
      preLoaderRoute: typeof WorkConsulteaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/cothm': {
      id: '/work/cothm'
      path: '/work/cothm'
      fullPath: '/work/cothm'
      preLoaderRoute: typeof WorkCothmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/destinify': {
      id: '/work/destinify'
      path: '/work/destinify'
      fullPath: '/work/destinify'
      preLoaderRoute: typeof WorkDestinifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/fidato': {
      id: '/work/fidato'
      path: '/work/fidato'
      fullPath: '/work/fidato'
      preLoaderRoute: typeof WorkFidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/freela': {
      id: '/work/freela'
      path: '/work/freela'
      fullPath: '/work/freela'
      preLoaderRoute: typeof WorkFreelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/little-paradise': {
      id: '/work/little-paradise'
      path: '/work/little-paradise'
      fullPath: '/work/little-paradise'
      preLoaderRoute: typeof WorkLittleParadiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/marketeria': {
      id: '/work/marketeria'
      path: '/work/marketeria'
      fullPath: '/work/marketeria'
      preLoaderRoute: typeof WorkMarketeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/meridian-realty': {
      id: '/work/meridian-realty'
      path: '/work/meridian-realty'
      fullPath: '/work/meridian-realty'
      preLoaderRoute: typeof WorkMeridianRealtyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/sunny-side': {
      id: '/work/sunny-side'
      path: '/work/sunny-side'
      fullPath: '/work/sunny-side'
      preLoaderRoute: typeof WorkSunnySideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/techdose': {
      id: '/work/techdose'
      path: '/work/techdose'
      fullPath: '/work/techdose'
      preLoaderRoute: typeof WorkTechdoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects/': {
      id: '/_authenticated/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminProjectsIndexRoute: typeof AuthenticatedAdminProjectsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
  AuthenticatedAdminProjectsIndexRoute: AuthenticatedAdminProjectsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HeroPreviewRoute: HeroPreviewRoute,
  MediaSplatRoute: MediaSplatRoute,
  WorkAgrinovaRoute: WorkAgrinovaRoute,
  WorkArtifyRoute: WorkArtifyRoute,
  WorkArtifyIdentityRoute: WorkArtifyIdentityRoute,
  WorkBakeryRoute: WorkBakeryRoute,
  WorkBlissHavenRoute: WorkBlissHavenRoute,
  WorkBridaStoneRoute: WorkBridaStoneRoute,
  WorkConsulteaseRoute: WorkConsulteaseRoute,
  WorkCothmRoute: WorkCothmRoute,
  WorkDestinifyRoute: WorkDestinifyRoute,
  WorkFidatoRoute: WorkFidatoRoute,
  WorkFreelaRoute: WorkFreelaRoute,
  WorkLittleParadiseRoute: WorkLittleParadiseRoute,
  WorkMarketeriaRoute: WorkMarketeriaRoute,
  WorkMeridianRealtyRoute: WorkMeridianRealtyRoute,
  WorkSunnySideRoute: WorkSunnySideRoute,
  WorkTechdoseRoute: WorkTechdoseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
